# ****Author : Anand Kumar Srivastava****

***Oasis Infobyte : April 2023***

**TASK-3 Car Price Prediction**

**Importing necessary Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Loading Dataset**

In [2]:
df=pd.read_excel('car price.xlsx')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

**Information About Dataset**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [4]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [5]:
df.corr()*100

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15144\4108046058.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()*100

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
car_ID,100.000000,-15.162114,12.972878,17.063639,5.238661,25.596004,7.196156,-3.392984,26.006368,-16.082362,15.027591,-1.500557,-20.378920,1.594004,1.125532,-10.909334
symboling,-15.162114,100.000000,-53.195368,-35.761152,-23.291906,-54.103820,-22.769059,-10.578971,-13.005136,-0.873514,-17.851508,7.087272,27.360625,-3.582263,3.460600,-7.997822
wheelbase,12.972878,-53.195368,100.000000,87.458748,79.514364,58.943476,77.638633,56.932868,48.874988,16.095905,24.978585,35.329448,-36.046875,-47.041361,-54.408192,57.781560
carlength,17.063639,-35.761152,87.458748,100.000000,84.111827,49.102946,87.772846,68.335987,60.645436,12.953261,15.841371,55.262297,-28.724220,-67.090866,-70.466160,68.292002
carwidth,5.238661,-23.291906,79.514364,84.111827,100.000000,27.921032,86.703246,73.543340,55.914991,18.294169,18.112863,64.073208,-22.001230,-64.270434,-67.721792,75.932530
carheight,25.596004,-54.103820,58.943476,49.102946,27.921032,100.000000,29.557173,6.714874,17.107092,-5.530667,26.121423,-10.880206,-32.041072,-4.863963,-10.735763,11.933623
curbweight,7.196156,-22.769059,77.638633,87.772846,86.703246,29.557173,100.000000,85.059407,64.847975,16.879004,15.136174,75.073925,-26.624318,-75.741378,-79.746479,83.530488
enginesize,-3.392984,-10.578971,56.932868,68.335987,73.543340,6.714874,85.059407,100.000000,58.377433,20.312859,2.897136,80.976865,-24.465983,-65.365792,-67.746991,87.414480
boreratio,26.006368,-13.005136,48.874988,60.645436,55.914991,17.107092,64.847975,58.377433,100.000000,-5.590898,0.519734,57.367682,-25.497553,-58.453172,-58.701178,55.317324
stroke,-16.082362,-0.873514,16.095905,12.953261,18.294169,-5.530667,16.879004,20.312859,-5.590898,100.000000,18.611011,8.093954,-6.796375,-4.214475,-4.393093,7.944308
compressionratio,15.027591,-17.851508,24.978585,15.841371,18.112863,26.121423,15.136174,2.897136,0.519734,18.611011,100.000000,-20.432623,-43.574051,32.470142,26.520139,6.798351
horsepower,-1.500557,7.087272,35.329448,55.262297,64.073208,-10.880206,75.073925,80.976865,57.367682,8.093954,-20.432623,100.000000,13.107251,-80.145618,-77.054389,80.813882
peakrpm,-20.378920,27.360625,-36.046875,-28.724220,-22.001230,-32.041072,-26.624318,-24.465983,-25.497553,-6.796375,-43.574051,13.107251,100.000000,-11.354438,-5.427481,-8.526715
citympg,1.594004,-3.582263,-47.041361,-67.090866,-64.270434,-4.863963,-75.741378,-65.365792,-58.453172,-4.214475,32.470142,-80.145618,-11.354438,100.000000,97.133704,-68.575134
highwaympg,1.125532,3.460600,-54.408192,-70.466160,-67.721792,-10.735763,-79.746479,-67.746991,-58.701178,-4.393093,26.520139,-77.054389,-5.427481,97.133704,100.000000,-69.759909
price,-10.909334,-7.997822,57.781560,68.292002,75.932530,11.933623,83.530488,87.414480,55.317324,7.944308,6.798351,80.813882,-8.526715,-68.575134,-69.759909,100.000000

In [6]:
df=df.drop(columns=["car_ID",'CarName','enginetype','cylindernumber','fueltype','aspiration','fuelsystem','doornumber','carbody','drivewheel','enginelocation'])
df

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,114,5400,19,25,22625.0

In [7]:
x=df.iloc[:,:-1]
x.head()

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22

In [8]:
y=df['price']
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

**Loading The Model**

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
73,0,120.9,208.1,71.7,56.7,3900,308,3.80,3.35,8.0,184,4500,14,16
104,3,91.3,170.7,67.9,49.7,3071,181,3.43,3.27,9.0,160,5200,19,25
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
112,0,107.9,186.7,68.4,56.7,3252,152,3.70,3.52,21.0,95,4150,28,33
52,1,93.1,159.1,64.2,54.1,1905,91,3.03,3.15,9.0,68,5000,31,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,2,97.3,171.7,65.5,55.7,2319,97,3.01,3.40,23.0,68,4500,37,42
77,2,93.7,157.3,64.4,50.8,1944,92,2.97,3.23,9.4,68,5500,31,38
79,1,93.0,157.3,63.8,50.8,2145,98,3.03,3.39,7.6,102,5500,24,30
147,0,97.0,173.5,65.4,53.0,2455,108,3.62,2.64,9.0,94,5200,25,31
140,2,93.3,157.3,63.8,55.7,2240,108,3.62,2.64,8.7,73,4400,26,31

In [12]:
model=LinearRegression()

In [13]:
model.fit(x_train,y_train)

LinearRegression()

In [14]:
ypred=model.predict(x_test)
ypred

array([16656.25609309, 17020.03026773,  9254.52333461, 14126.98601483,
        5449.51857065, 24369.13750008,  6777.34239055,  6103.38601453,
        5355.99628882, 13145.31596437,  6403.45717434,  9543.85424201,
        5919.50282383, 10117.13582828,  7777.04976848, 16491.22018403,
       47366.37868166, 10426.31897132, 17601.90975207, 13434.92358383,
       10272.69421396, 17583.86534997,  6939.80617364,  1370.00055324,
       10064.7322103 ,  9035.73853918, 13193.08814966,  6891.9176448 ,
        5823.03789264, 15215.67822684, 17552.09588886,  5274.3011682 ,
        9349.36877389,  6932.76796937,  8940.46043466,  7865.21428582,
       24168.2663525 , 23978.41523253, 14359.89601193, 25664.83748663,
       38311.23346602, 18910.33150258,  7662.92152489,  9201.6886586 ,
       10268.06987429, 16497.06221013,  5556.60898722,  8694.30394733,
       27496.6330209 , 27496.6330209 , 10355.85899493, 10847.83200743,
       10215.19078507, 14185.03620095,  9511.26649298, 13891.92681613,
       17789.29766297, 10848.79176256,  9660.69879443, 16826.87918537,
       21456.58831253, 12734.29364806])

In [15]:
from sklearn.metrics import r2_score as r

In [16]:
r(y_test,ypred)*100

80.7903969957876